// SPDX-License-Identifier: MIT
// Copyright (c) 2026 rafaqat
/**
 * Common 4-chord loops per genre and mode (M13.16) for gb_song template {variant: 1–3}: the loops heard most often in
 * the verses and choruses of songs tagged with the genre in Chordonomicon (Kantarelis et al. 2024, arXiv 2410.22046).
 * The dataset is CC BY-NC 4.0 and is not part of gb-mcp; only these common progressions — general musical facts — are.
 * Roman numerals, one chord per bar. pooled: too few songs carry the genre's tags (< 300 in that mode), so the loops
 * of all genres together. Generated by eval/m13-chords/common_loops.py — do not edit by hand.
 */
export type CommonLoops = { verse: readonly string[]; chorus: readonly string[]; pooled: boolean };
export const COMMON_LOOPS: Record<string, { major: CommonLoops; minor: CommonLoops }> = {
  "lo-fi hip-hop": {
    major: { verse: ["I | vi | IV | V", "I | vi | V | IV", "I | V | vi | IV"], chorus: ["I | V | vi | IV", "I | vi | IV | V", "vi | V | IV | I"], pooled: false },
    minor: { verse: ["i | VI | III | VII", "i | VII | VI | III", "i | VI | VII | III"], chorus: ["VI | III | i | VII", "i | VI | III | VII", "III | VI | i | VII"], pooled: false },
  },
  "R&B": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | IV | ii | V"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "IV | I | vi | V"], pooled: false },
    minor: { verse: ["i | VI | III | VII", "i | iv | VII | III", "i | VII | VI | iv"], chorus: ["i | VII | VI | iv", "i | VI | III | VII", "VI | VII | i | III"], pooled: false },
  },
  "ambient": {
    major: { verse: ["I | V | vi | IV", "I | IV | vi | V", "I | IV | V | vi"], chorus: ["vi | V | I | IV", "I | V | vi | IV", "IV | vi | I | V"], pooled: false },
    minor: { verse: ["i | VII | III | VI", "i | VI | VII | III", "i | VII | VI | III"], chorus: ["III | i | VII | VI", "i | VII | III | VI", "i | III | VI | VII"], pooled: false },
  },
  "jazz ballad": {
    major: { verse: ["I | vi | IV | V", "I | V | vi | IV", "I | iii | ii | V"], chorus: ["I | V | vi | IV", "I | vi | IV | V", "IV | I | vi | V"], pooled: false },
    minor: { verse: ["i | iv | VII | III", "i | VII | VI | V", "i | VI | VII | III"], chorus: ["i | VI | III | VII", "III | i | iv | VII", "i | VII | VI | V"], pooled: false },
  },
  "reggaeton": {
    major: { verse: ["I | vi | IV | V", "I | vi | ii | V", "I | IV | ii | V"], chorus: ["ii | IV | I | V", "I | vi | IV | V", "I | vi | ii | V"], pooled: false },
    minor: { verse: ["i | VII | iv | VI", "i | VII | VI | III", "i | VI | VII | III"], chorus: ["iv | i | III | VII", "iv | VI | i | VII", "i | VII | VI | III"], pooled: false },
  },
  "synthwave": {
    major: { verse: ["I | vi | IV | V", "I | vi | V | IV", "I | IV | ii | V"], chorus: ["IV | I | vi | V", "I | vi | IV | V", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | III | VI | VII", "i | VII | VI | III", "i | VI | VII | III"], chorus: ["VI | III | i | VII", "VI | VII | i | III", "i | VII | III | VI"], pooled: true },
  },
  "pop": {
    major: { verse: ["I | vi | IV | V", "I | vi | V | IV", "I | IV | vi | V"], chorus: ["IV | I | vi | V", "I | vi | IV | V", "I | V | ii | IV"], pooled: false },
    minor: { verse: ["i | III | VI | VII", "i | VII | VI | III", "i | VII | III | VI"], chorus: ["VI | III | i | VII", "VI | VII | i | III", "III | i | VI | VII"], pooled: false },
  },
  "afrobeats": {
    major: { verse: ["I | V | vi | IV", "I | vi | V | IV", "I | IV | ii | V"], chorus: ["IV | I | vi | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "funk": {
    major: { verse: ["I | vi | IV | V", "I | V | vi | IV", "I | vi | V | IV"], chorus: ["vi | IV | I | V", "I | vi | IV | V", "ii | V | I | IV"], pooled: false },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VI | VII | III"], chorus: ["i | III | VI | VII", "i | VI | III | VII", "i | iv | VI | VII"], pooled: false },
  },
  "indie rock": {
    major: { verse: ["I | vi | V | IV", "I | vi | IV | V", "I | V | ii | IV"], chorus: ["IV | V | I | vi", "IV | I | vi | V", "I | IV | vi | V"], pooled: false },
    minor: { verse: ["i | VI | III | VII", "i | VII | VI | III", "i | VI | VII | III"], chorus: ["III | i | VII | VI", "III | VII | i | VI", "VI | iv | i | VII"], pooled: false },
  },
  "deep house": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | vi | V | IV"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "techno": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | vi | V | IV"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "UK garage": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | vi | V | IV"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "trap": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | vi | V | IV"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "ii | IV | I | V"], pooled: false },
    minor: { verse: ["i | VI | III | VII", "i | VII | VI | iv", "i | VII | iv | VI"], chorus: ["VI | iv | i | VII", "i | VI | III | VII", "i | VII | VI | III"], pooled: false },
  },
  "drum and bass": {
    major: { verse: ["I | V | vi | IV", "I | vi | V | IV", "I | IV | ii | V"], chorus: ["IV | I | vi | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "EDM (big room)": {
    major: { verse: ["I | vi | V | IV", "I | V | ii | IV", "I | IV | vi | V"], chorus: ["I | vi | IV | V", "IV | I | vi | V", "ii | IV | I | V"], pooled: false },
    minor: { verse: ["i | VII | VI | III", "i | III | VI | VII", "i | III | VII | VI"], chorus: ["VI | VII | i | III", "VI | III | i | VII", "v | VI | VII | i"], pooled: false },
  },
  "classical/pop crossover": {
    major: { verse: ["I | vi | IV | V", "I | vi | V | IV", "I | IV | ii | V"], chorus: ["IV | I | vi | V", "I | vi | IV | V", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "ambient trance (William Orbit style)": {
    major: { verse: ["I | vi | V | IV", "I | IV | ii | V", "I | IV | vi | V"], chorus: ["I | IV | vi | V", "IV | I | vi | V", "ii | V | I | IV"], pooled: true },
    minor: { verse: ["i | III | VI | VII", "i | III | VII | VI", "i | VII | VI | iv"], chorus: ["iv | i | VII | VI", "VI | VII | i | III", "VI | i | III | VII"], pooled: false },
  },
  "Levantine ethereal strings (Fairuz style)": {
    major: { verse: ["I | V | vi | IV", "I | vi | V | IV", "I | IV | ii | V"], chorus: ["IV | I | vi | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "epic orchestral (Hans Zimmer style)": {
    major: { verse: ["I | vi | IV | V", "I | vi | V | IV", "I | IV | ii | V"], chorus: ["IV | I | vi | V", "I | vi | IV | V", "I | IV | vi | V"], pooled: false },
    minor: { verse: ["i | VI | VII | III", "i | III | VI | VII", "i | VII | VI | V"], chorus: ["VI | VII | i | III", "i | VI | VII | III", "VI | VII | v | i"], pooled: false },
  },
  "Latin trap": {
    major: { verse: ["I | vi | IV | V", "I | vi | V | IV", "I | IV | ii | V"], chorus: ["IV | I | vi | V", "I | vi | IV | V", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VII | iv | VI", "i | VII | VI | iv", "i | VII | VI | III"], chorus: ["VI | iv | i | VII", "iv | VI | i | VII", "iv | i | III | VII"], pooled: false },
  },
  "dembow": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | vi | V | IV"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "bachata": {
    major: { verse: ["I | V | vi | IV", "I | vi | V | IV", "I | IV | ii | V"], chorus: ["IV | I | vi | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "salsa": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | vi | V | IV"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "cumbia": {
    major: { verse: ["I | vi | IV | V", "I | V | vi | IV", "I | IV | ii | V"], chorus: ["I | V | vi | IV", "I | vi | IV | V", "I | IV | V | vi"], pooled: false },
    minor: { verse: ["i | iv | VII | III", "i | VII | III | V", "i | iv | VII | V"], chorus: ["i | VI | III | VII", "III | V | i | VI", "i | VII | VI | V"], pooled: false },
  },
  "bossa nova": {
    major: { verse: ["I | IV | ii | V", "I | vi | ii | V", "I | vi | IV | V"], chorus: ["I | vi | IV | V", "IV | ii | V | I", "vi | IV | I | V"], pooled: false },
    minor: { verse: ["i | iv | VII | III", "i | iv | VII | V", "i | III | VI | V"], chorus: ["III | VI | V | i", "III | i | iv | VII", "i | iv | VII | V"], pooled: false },
  },
  "corridos tumbados": {
    major: { verse: ["I | IV | ii | V", "I | iii | IV | V", "I | vi | ii | V"], chorus: ["ii | V | I | vi", "IV | ii | V | I", "ii | IV | V | I"], pooled: false },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "Latin pop": {
    major: { verse: ["I | vi | IV | V", "I | IV | ii | V", "I | vi | ii | V"], chorus: ["I | IV | ii | V", "I | vi | IV | V", "vi | V | IV | I"], pooled: false },
    minor: { verse: ["i | iv | VII | III", "i | VI | VII | III", "i | iv | VII | V"], chorus: ["VI | VII | III | i", "iv | VII | III | i", "i | VII | VI | V"], pooled: false },
  },
  "Brazilian funk": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | vi | V | IV"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "merengue": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | vi | V | IV"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "Arabic pop": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | vi | V | IV"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "Khaleeji": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | vi | V | IV"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "mahraganat": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | vi | V | IV"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "ra\u00ef": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | vi | V | IV"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "gnawa": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | vi | V | IV"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "Moroccan chaabi": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | vi | V | IV"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "dabke": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | vi | V | IV"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "country": {
    major: { verse: ["I | vi | IV | V", "I | vi | V | IV", "I | IV | ii | V"], chorus: ["IV | I | vi | V", "I | vi | IV | V", "I | IV | vi | V"], pooled: false },
    minor: { verse: ["i | VII | VI | III", "i | VI | VII | III", "i | VII | III | VI"], chorus: ["III | i | VI | VII", "VI | III | i | VII", "i | III | VII | VI"], pooled: false },
  },
  "Americana": {
    major: { verse: ["I | vi | IV | V", "I | vi | V | IV", "I | IV | vi | V"], chorus: ["IV | I | vi | V", "IV | V | I | vi", "IV | V | vi | I"], pooled: false },
    minor: { verse: ["i | VI | III | VII", "i | VII | VI | III", "i | VI | VII | III"], chorus: ["VI | III | i | VII", "i | VI | III | VII", "VI | VII | i | III"], pooled: false },
  },
  "Bollywood (filmi)": {
    major: { verse: ["I | IV | ii | V", "I | vi | V | IV", "I | ii | IV | V"], chorus: ["vi | V | IV | I", "I | IV | ii | V", "I | V | vi | IV"], pooled: false },
    minor: { verse: ["i | v | VI | VII", "i | VI | VII | III", "i | VI | III | VII"], chorus: ["i | VII | VI | V", "i | VI | III | VII", "III | i | VI | VII"], pooled: false },
  },
  "gospel": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | IV | ii | V"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "IV | I | vi | V"], pooled: false },
    minor: { verse: ["i | VI | III | VII", "i | VI | VII | III", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "III | VI | i | VII"], pooled: false },
  },
  "soul": {
    major: { verse: ["I | IV | ii | V", "I | vi | ii | V", "I | V | vi | IV"], chorus: ["I | vi | ii | V", "ii | V | I | IV", "I | vi | V | IV"], pooled: false },
    minor: { verse: ["i | VI | III | VII", "i | iv | VII | III", "i | VII | VI | III"], chorus: ["III | i | iv | VII", "i | VI | III | VII", "i | VII | VI | V"], pooled: false },
  },
  "blues": {
    major: { verse: ["I | vi | IV | V", "I | IV | ii | V", "I | V | vi | IV"], chorus: ["I | V | vi | IV", "I | vi | IV | V", "vi | V | IV | I"], pooled: false },
    minor: { verse: ["i | VII | VI | V", "i | VI | VII | III", "i | VI | III | VII"], chorus: ["i | VI | III | VII", "i | VII | VI | V", "III | i | VI | VII"], pooled: false },
  },
  "Celtic folk": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | vi | V | IV"], chorus: ["IV | V | I | vi", "I | V | vi | IV", "IV | ii | V | I"], pooled: false },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VI | VII | III"], chorus: ["III | i | VI | VII", "III | VII | i | VI", "III | VII | v | i"], pooled: false },
  },
  "lullaby": {
    major: { verse: ["I | vi | IV | V", "I | IV | ii | V", "I | ii | V | IV"], chorus: ["I | IV | ii | V", "I | vi | IV | V", "I | vi | ii | V"], pooled: false },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
  "K-pop": {
    major: { verse: ["I | IV | ii | V", "I | vi | IV | V", "I | vi | ii | V"], chorus: ["ii | V | I | vi", "ii | V | I | IV", "I | vi | IV | V"], pooled: false },
    minor: { verse: ["i | v | VI | VII", "i | VI | VII | III", "i | VII | VI | V"], chorus: ["VI | VII | i | III", "VI | VII | i | v", "i | iv | VII | III"], pooled: false },
  },
  "amapiano": {
    major: { verse: ["I | V | vi | IV", "I | vi | IV | V", "I | vi | V | IV"], chorus: ["I | vi | IV | V", "I | V | vi | IV", "I | IV | vi | V"], pooled: true },
    minor: { verse: ["i | VI | III | VII", "i | III | VI | VII", "i | VII | VI | III"], chorus: ["VI | VII | i | III", "i | VI | III | VII", "i | VII | III | VI"], pooled: true },
  },
};
