// SPDX-License-Identifier: MIT
// Copyright (c) 2026 rafaqat
/**
 * M10: notes generated by the Anticipatory Music Transformer (absolute seconds) → Song JSON `notes` for one section.
 * Each bar is written as (beats × 4) equal shares — 16ths — so a note's length is its count of 16ths ("g4@2").
 * Notes starting together become a chord as long as its longest member; a note is cut where the next one starts or
 * where the section ends; a note crossing a bar line is struck again in the next bar (Song JSON writes bar by bar).
 */
export type InfillNote = { pitch: number; start_s: number; dur_s: number };
export type SectionTiming = { startS: number; bpm: number; beatsPerBar: number; bars: number };

const NAMES = ["c", "c#", "d", "d#", "e", "f", "f#", "g", "g#", "a", "a#", "b"];
const noteName = (pitch: number) => `${NAMES[pitch % 12]}${Math.floor(pitch / 12) - 1}`;

export function notesToPart(notes: readonly InfillNote[], t: SectionTiming): string {
  const sixteenth = 60 / t.bpm / 4;
  const perBar = t.beatsPerBar * 4;
  const total = t.bars * perBar;
  const onsets = new Map<number, { pitches: Set<number>; len: number }>();
  for (const n of notes) {
    const slot = Math.round((n.start_s - t.startS) / sixteenth);
    if (slot < 0 || slot >= total) continue;
    const o = onsets.get(slot) ?? { pitches: new Set<number>(), len: 1 };
    o.pitches.add(n.pitch);
    o.len = Math.max(o.len, Math.max(1, Math.round(n.dur_s / sixteenth)));
    onsets.set(slot, o);
  }
  const starts = [...onsets.keys()].sort((a, b) => a - b);
  starts.forEach((s, i) => { const o = onsets.get(s)!; o.len = Math.min(o.len, (starts[i + 1] ?? total) - s); });

  const bars: string[] = [];
  for (let b = 0; b < t.bars; b++) {
    const end = (b + 1) * perBar;
    const tokens: string[] = [];
    let sounding = false;
    for (let slot = b * perBar; slot < end;) {
      const o = onsets.get(slot);
      if (!o) { tokens.push("~"); slot++; continue; }
      const len = Math.min(o.len, end - slot);
      if (o.len > len && !onsets.has(end)) onsets.set(end, { pitches: o.pitches, len: o.len - len }); // struck again next bar
      const pitches = [...o.pitches].sort((x, y) => x - y).map(noteName);
      const name = pitches.length > 1 ? `[${pitches.join(",")}]` : pitches[0]!;
      tokens.push(len > 1 ? `${name}@${len}` : name);
      sounding = true;
      slot += len;
    }
    bars.push(sounding ? tokens.join(" ") : `~@${perBar}`);
  }
  return bars.join(" | ");
}
