// SPDX-License-Identifier: MIT
// Copyright (c) 2026 rafaqat
/** GM program → GarageBand 10.4.14 patch, probed automatically (one MIDI file per program opened in GarageBand). Generated from gm-patch-map.json. */
export const GM_PATCH_MAP: Readonly<Record<number, { gm: string; patch: string }>> = {
  0: { gm: "Acoustic Grand Piano", patch: "Steinway Grand Piano" },
  1: { gm: "Bright Acoustic Piano", patch: "Steinway Grand Piano" },
  2: { gm: "Electric Grand Piano", patch: "Steinway Grand Piano" },
  3: { gm: "Honky-tonk Piano", patch: "Steinway Grand Piano" },
  4: { gm: "Electric Piano 1", patch: "Classic Electric Piano" },
  5: { gm: "Electric Piano 2", patch: "FM Piano" },
  6: { gm: "Harpsichord", patch: "Classic D6" },
  7: { gm: "Clavinet", patch: "Classic D6" },
  8: { gm: "Celesta", patch: "Delicate Bells" },
  9: { gm: "Glockenspiel", patch: "Glockenspiel" },
  10: { gm: "Music Box", patch: "Glockenspiel" },
  11: { gm: "Vibraphone", patch: "Vibraphone" },
  12: { gm: "Marimba", patch: "Marimba" },
  13: { gm: "Xylophone", patch: "Delicate Bells" },
  14: { gm: "Tubular Bells", patch: "Soft Synth Bells" },
  15: { gm: "Dulcimer", patch: "Classical Acoustic Guitar" },
  16: { gm: "Drawbar Organ", patch: "Tonewheel Organ" },
  17: { gm: "Percussive Organ", patch: "Bebop Organ" },
  18: { gm: "Rock Organ", patch: "Classic Rock Organ" },
  19: { gm: "Church Organ", patch: "Wedding Organ" },
  20: { gm: "Reed Organ", patch: "Noble Organ" },
  21: { gm: "Accordion", patch: "Toccata Organ" },
  22: { gm: "Harmonica", patch: "Mellow Organ" },
  23: { gm: "Tango Accordion", patch: "Mellow Organ" },
  24: { gm: "Acoustic Guitar (nylon)", patch: "Classical Acoustic Guitar" },
  25: { gm: "Acoustic Guitar (steel)", patch: "Acoustic Guitar" },
  26: { gm: "Electric Guitar (jazz)", patch: "Roots Rock" },
  27: { gm: "Electric Guitar (clean)", patch: "Classic Clean" },
  28: { gm: "Electric Guitar (muted)", patch: "Classic Clean" },
  29: { gm: "Overdriven Guitar", patch: "Hard Rock" },
  30: { gm: "Distortion Guitar", patch: "Hard Rock" },
  31: { gm: "Guitar Harmonics", patch: "Acoustic Guitar" },
  32: { gm: "Acoustic Bass", patch: "Upright Studio Bass" },
  33: { gm: "Electric Bass (finger)", patch: "Fingerstyle Bass" },
  34: { gm: "Electric Bass (pick)", patch: "Picked Bass" },
  35: { gm: "Fretless Bass", patch: "Muted Bass" },
  36: { gm: "Slap Bass 1", patch: "Picked Bass" },
  37: { gm: "Slap Bass 2", patch: "Picked Bass" },
  38: { gm: "Synth Bass 1", patch: "Metro Bass" },
  39: { gm: "Synth Bass 2", patch: "Taureg Moon Bass" },
  40: { gm: "Violin", patch: "String Ensemble" },
  41: { gm: "Viola", patch: "String Ensemble" },
  42: { gm: "Cello", patch: "String Ensemble" },
  43: { gm: "Contrabass", patch: "String Ensemble" },
  44: { gm: "Tremolo Strings", patch: "String Ensemble" },
  45: { gm: "Pizzicato Strings", patch: "String Ensemble" },
  46: { gm: "Orchestral Harp", patch: "Harp" },
  47: { gm: "Timpani", patch: "Orchestral Kit" },
  48: { gm: "String Ensemble 1", patch: "String Ensemble" },
  49: { gm: "String Ensemble 2", patch: "String Ensemble" },
  50: { gm: "Synth Strings 1", patch: "Bright Synth Strings" },
  51: { gm: "Synth Strings 2", patch: "Epic Synth Strings" },
  52: { gm: "Choir Aahs", patch: "Classical Ensemble" },
  53: { gm: "Voice Oohs", patch: "Classical Ensemble" },
  54: { gm: "Synth Voice", patch: "Dream Voice" },
  55: { gm: "Orchestra Hit", patch: "Full Brass" },
  56: { gm: "Trumpet", patch: "Trumpets" },
  57: { gm: "Trombone", patch: "Trombones" },
  58: { gm: "Tuba", patch: "Tuba" },
  59: { gm: "Muted Trumpet", patch: "Full Brass" },
  60: { gm: "French Horn", patch: "French Horns" },
  61: { gm: "Brass Section", patch: "Full Brass" },
  62: { gm: "Synth Brass 1", patch: "Bright Synth Brass" },
  63: { gm: "Synth Brass 2", patch: "Bright Synth Brass" },
  64: { gm: "Soprano Sax", patch: "Saxophone" },
  65: { gm: "Alto Sax", patch: "Saxophone" },
  66: { gm: "Tenor Sax", patch: "Saxophone" },
  67: { gm: "Baritone Sax", patch: "Saxophone" },
  68: { gm: "Oboe", patch: "Oboe" },
  69: { gm: "English Horn", patch: "Bassoon Solo" },
  70: { gm: "Bassoon", patch: "Bassoon Solo" },
  71: { gm: "Clarinet", patch: "Clarinet Solo" },
  72: { gm: "Piccolo", patch: "Flute Solo" },
  73: { gm: "Flute", patch: "Flute Solo" },
  74: { gm: "Recorder", patch: "Flute Solo" },
  75: { gm: "Pan Flute", patch: "Boarding Area" },
  76: { gm: "Blown Bottle", patch: "Airways" },
  77: { gm: "Shakuhachi", patch: "Flute Solo" },
  78: { gm: "Whistle", patch: "Flute Solo" },
  79: { gm: "Ocarina", patch: "Flute Solo" },
  80: { gm: "Lead 1 (square)", patch: "Reverse Engineering" },
  81: { gm: "Lead 2 (sawtooth)", patch: "Soft Saw Lead" },
  82: { gm: "Lead 3 (calliope)", patch: "Deep Organ" },
  83: { gm: "Lead 4 (chiff)", patch: "Emotive Pulse" },
  84: { gm: "Lead 5 (charang)", patch: "Sync Lead" },
  85: { gm: "Lead 6 (voice)", patch: "Dream Voice" },
  86: { gm: "Lead 7 (fifths)", patch: "Power Fifths" },
  87: { gm: "Lead 8 (bass + lead)", patch: "Soft Square Lead" },
  88: { gm: "Pad 1 (new age)", patch: "Glistening Pad" },
  89: { gm: "Pad 2 (warm)", patch: "Classic Analog Pad" },
  90: { gm: "Pad 3 (polysynth)", patch: "Epic Cloud Formation" },
  91: { gm: "Pad 4 (choir)", patch: "Dream Voice" },
  92: { gm: "Pad 5 (bowed)", patch: "Rain Clouds" },
  93: { gm: "Pad 6 (metallic)", patch: "Ghost Voices" },
  94: { gm: "Pad 7 (halo)", patch: "Glistening Pad" },
  95: { gm: "Pad 8 (sweep)", patch: "Slow Drift" },
  96: { gm: "FX 1 (rain)", patch: "Event Horizon" },
  97: { gm: "FX 2 (soundtrack)", patch: "Event Horizon" },
  98: { gm: "FX 3 (crystal)", patch: "Glass Sky" },
  99: { gm: "FX 4 (atmosphere)", patch: "Stratosphere" },
  100: { gm: "FX 5 (brightness)", patch: "Glass Sky" },
  101: { gm: "FX 6 (goblins)", patch: "Wave Space" },
  102: { gm: "FX 7 (echoes)", patch: "Pulsating Waves" },
  103: { gm: "FX 8 (sci-fi)", patch: "Jitter Strings" },
  104: { gm: "Sitar", patch: "Acoustic Guitar" },
  105: { gm: "Banjo", patch: "Acoustic Guitar" },
  106: { gm: "Shamisen", patch: "Acoustic Guitar" },
  107: { gm: "Koto", patch: "Harp" },
  108: { gm: "Kalimba", patch: "Marimba" },
  109: { gm: "Bagpipe", patch: "Saxophone" },
  110: { gm: "Fiddle", patch: "String Ensemble" },
  111: { gm: "Shanai", patch: "Saxophone" },
  112: { gm: "Tinkle Bell", patch: "Delicate Bells" },
  113: { gm: "Agogo", patch: "Orchestral Kit" },
  114: { gm: "Steel Drums", patch: "Vibraphone" },
  115: { gm: "Woodblock", patch: "Vibraphone" },
  116: { gm: "Taiko Drum", patch: "Orchestral Kit" },
  117: { gm: "Melodic Tom", patch: "Orchestral Kit" },
  118: { gm: "Synth Drum", patch: "Boutique 808" },
  119: { gm: "Reverse Cymbal", patch: "Boutique 808" },
  120: { gm: "Guitar Fret Noise", patch: "Acoustic Guitar" },
  121: { gm: "Breath Noise", patch: "Breathy Vox" },
  122: { gm: "Seashore", patch: "Sea of Glass" },
  123: { gm: "Bird Tweet", patch: "Zen Garden" },
  124: { gm: "Telephone Ring", patch: "Electron Echoes" },
  125: { gm: "Helicopter", patch: "Wave Space" },
  126: { gm: "Applause", patch: "Stratosphere" },
  127: { gm: "Gunshot", patch: "Rising High Synth Lead" },
};

/** Channel-10 drum kits: GM program → GarageBand kit. */
export const GM_DRUM_KIT_MAP: Readonly<Record<number, string>> = {
  0: "SoCal",
  8: "Retro Rock",
  16: "Epic Electro",
  24: "Boutique 808",
  25: "Boutique 808",
  32: "Roots",
  40: "Orchestral Kit",
  48: "Orchestral Kit",
  56: "Orchestral Kit",
};

export const patchFor = (program: number, channel: number): string | undefined =>
  channel === 10 ? GM_DRUM_KIT_MAP[program] : GM_PATCH_MAP[program]?.patch;
